# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: JC's Code Dwelling Place
email: jingxian-chen@outlook.com
description: Selected coding projects in genomics, proteomics, single-cell RNA-seq, NGS, and high-throughput quantitative image analysis.
# description: >- # this means to ignore newlines until "baseurl:"
#   Selected coding projects in genomics, proteomics, single-cell RNA-seq, NGS, and high-throughput quantitative image analysis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb # Comment Out if you don't want twitter to show up in the side bar
github_username:  jc271828
logo: /assets/website_logo_100_pixel_square_no_background.png

# Build settings
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
  # - jekyll-feed # Comment out if you don't want the subscribe button to show up in the side bar

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
